color_0 = "#FF000000" #background

color_1 = "#FF31C400"	#River source
color_2 = "#FFFFFFFF"	#River body
color_3 = "#FFDEB500"	#River end (not used currently)
color_4 = "#FF002DD1"	#River waterfall
color_5 = "#FFB80003"	#River waterfalls multiple

color_100 = "#882FFFE7" #other